### ISSUE TITLE
[JOSS review] Some morphology functionality is not available

### ISSUE THREAD

**Issue by mstimberg** [ZeitgeberH/patchview#10]
Loading the `test.asc` morphology, I am not able to use "Sholl analysis" (prints "To be done!" on the command line), and "Update Cell names" and "Distance to Pia" do not seem to work either (errors on the command line, see below). I am also not quite sure how to test the [Plotting somas for a group of neurons](https://patchview.readthedocs.io/en/latest/introduction.html#plotting-somas-for-a-group-of-neurons) functionality – does this require a single file with multiple cells in it? I tried loading the same cell several times, but this leads to a broken display.

Error for "Update Cell names" (after loading a cell three times):
```pytb
Traceback (most recent call last):
  File "/mnt/data/miniforge3/envs/patchview/lib/python3.8/site-packages/patchview/patchview.py", line 6803, in morph_analysis_event
    self.updateInterCellDistance()
  File "/mnt/data/miniforge3/envs/patchview/lib/python3.8/site-packages/patchview/patchview.py", line 6747, in updateInterCellDistance
    summary.item(j, 9).value[p]
IndexError: invalid index to scalar variable.
```
Error for "Distance to Pia":
```pytb
Traceback (most recent call last):
  File "/mnt/data/miniforge3/envs/patchview/lib/python3.8/site-packages/patchview/patchview.py", line 6805, in morph_analysis_event
    self.measureDist2Pia()
  File "/mnt/data/miniforge3/envs/patchview/lib/python3.8/site-packages/patchview/patchview.py", line 6765, in measureDist2Pia
    if self.pia is not None:
AttributeError: 'MainWindow' object has no attribute 'pia'
```

openjournals/joss-reviews#4706

**Comment by ZeitgeberH** [comment]
Hi,
I've fixed "Sholl analysis" part. Please see documentation [here](https://patchview.readthedocs.io/en/latest/tutorials.html#morphological-data).
 You are right about the [Plotting somas for a group of neurons](https://patchview.readthedocs.io/en/latest/introduction.html#plotting-somas-for-a-group-of-neurons) functionality. It only works for reconstruction file with multiple cells in it (like this[ one](https://github.com/ZeitgeberH/patchview/blob/main/tests/data/test_multiSoma.ASC)). Likewise,  "Update Cell names"  is only useful under this  situation. 
"Distance to Pia" only works if the[ ASC file](https://github.com/ZeitgeberH/patchview/blob/main/tests/data/test_multiSoma.ASC) actually has an entry named "Pia" .
Documentation of the [these functions](https://patchview.readthedocs.io/en/latest/tutorials.html#morphological-data) has been updated. 
Thanks!

**Comment by mstimberg** [comment]
I did a quick check with the provided files, and everything seems to work as intended now. Thanks.
