### ISSUE TITLE
[JOSS review] Consider reading configuration file from standard directory

### ISSUE THREAD

**Issue by mstimberg** [ZeitgeberH/patchview#11]
The configuration currently needs to be changed in the installation directory, which can be problematic (e.g. a system-wide installation) since the user does not necessarily has write privileges for this directory. A better solution would be to check for a configuration file in a standard configuration directory (e.g. by using https://github.com/ActiveState/appdirs).

openjournals/joss-reviews#4706

**Comment by ZeitgeberH** [comment]
I've updated the configure file location using appdirs. It works (see documentation [here](https://patchview.readthedocs.io/en/latest/installation.html#configuration)) great under Windows and Ubuntu. 
Thanks for your suggestion.

**Comment by mstimberg** [comment]
Works like a charm, thanks!
