### ISSUE TITLE
Hi from NWB!

### ISSUE THREAD

**Issue by bendichter** [ZeitgeberH/patchview#13]
We were excited to see you cited the new NWB eLife paper in your recent publication on this software. We see that you export data to NWB. Do you also read NWB files?

We would like to invite you to submit a PR including a description of your software in our gallery of supported tools [here](https://nwb-overview.readthedocs.io/en/latest/tools/tools_home.html).

**Comment by ZeitgeberH** [comment]
Hi @bendichter 
Yes, Patchview converts Heka or Axon file format for patch-clamp data, exports to NWB files. It has APIs to read those NWB files . A quick demo  [here](https://patchview.readthedocs.io/en/latest/APIs.html#nwb-neurodatawithoutborders-apis). 

Thanks for the invitation. The gallery looks awesome. We will submit a PR soon.

**Comment by bendichter** [comment]
Excellent!

**Comment by ZeitgeberH** [comment]
A [PR](https://github.com/NeurodataWithoutBorders/nwb-overview/pull/70) is submitted.
Thanks!
