### ISSUE TITLE
pip install and local install both fail

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [ZeitgeberH/patchview#17]
**Describe the bug**
Installation of patch view with pip and from local package both fail on macOS Monterey 12.6.3. Perhaps I am missing something needed for installation to work? Or I need to change version of something?

**To Reproduce Bug 1 of 2**
Steps to reproduce failed install via pip:
1. `conda create -n patchview python=3.8`
2. `pip install patchview`

**Expected behavior**
patchview installed.

**Actual behavior**
Install fails with error message:
```
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
patchview depends on NeuroM@ git+https://github.com/ZeitgeberH/NeuroM@patchview#egg=NeuroM
```

**To Reproduce Bug 2 of 2**
Steps to reproduce failed local install:
1. clone this repo and cd to local repo
2. `conda env create -f enviroment.yml` <-- spelling error is in the repo
3. `conda activate patchviewPy3`
4. `pip install -r requirements.txt`

**Expected behavior**
All requirements for patchview installed in patchviewPy3 environment.

**Actual behavior**
Install fails with error message:
```
  ERROR: Command errored out with exit status 1:
   command: /Users/marcel/opt/miniconda3/envs/patchviewPy3/bin/python /Users/marcel/opt/miniconda3/envs/patchviewPy3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/tm/5dps4bkx489b0qrcxckh0gq40000gn/T/tmpmxie4rv5
       cwd: /private/var/folders/tm/5dps4bkx489b0qrcxckh0gq40000gn/T/pip-install-vo7mqvhe/pycairo_1460a60ac34f4f6ea46644460e789845
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-cpython-39
  creating build/lib.macosx-10.9-x86_64-cpython-39/cairo
  copying cairo/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/cairo
  copying cairo/__init__.pyi -> build/lib.macosx-10.9-x86_64-cpython-39/cairo
  copying cairo/py.typed -> build/lib.macosx-10.9-x86_64-cpython-39/cairo
  running build_ext
  'pkg-config' not found.
  Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
```

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.3

**Comment by ZeitgeberH** [comment]
Hi @marcel-goldschen-ohm 
Thanks for testing out Patchview and report the issues.
For now, please local install (Your approach 2) `Patchview` from source. 
To resolve the issues above,
First, please check if package `cairo` is installed in  you OS, otherwise do:
`brew install cairo `

There are three packages (`NeuroM`, `dictdiffer`, `pyemf3`) that we pull directly from github. You can install them via:
```
pip install git+https://github.com/ZeitgeberH/NeuroM@patchview#egg=NeuroM git+https://github.com/ZeitgeberH/dictdiffer#egg=dictdiffer git+https://github.com/jeremysanders/pyemf3#egg=pyemf3`
```

From there, proceed with 
```
pip install -r requirements.txt

pip install -e .
```
Please let me know if this helps. 
Thanks!

**Comment by marcel-goldschen-ohm** [comment]
Thanks for the suggestions, but neither approach worked and in both cases `pycairo` seems to be the problem.

**1st approach:**
After pip installing the GitHub repos you indicated (which appears to have worked), the subsequent `pip install patchview` command still fails with error:
```
Building wheel for pycairo (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycairo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-38
      creating build/lib.macosx-10.9-x86_64-cpython-38/cairo
      copying cairo/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-38/cairo
      copying cairo/__init__.pyi -> build/lib.macosx-10.9-x86_64-cpython-38/cairo
      copying cairo/py.typed -> build/lib.macosx-10.9-x86_64-cpython-38/cairo
      running build_ext
      'pkg-config' not found.
      Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycairo
Successfully built patchview future
Failed to build pycairo
ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
```


**2nd approach:**
`brew install cairo` appears to have worked (no errors). However, `pip install -r requirements.txt` continues to fail with error:
```
Building wheel for pycairo (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/.../opt/miniconda3/envs/patchviewPy3/bin/python /Users/.../opt/miniconda3/envs/patchviewPy3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/tm/5dps4bkx489b0qrcxckh0gq40000gn/T/tmpu8yuo6r0
       cwd: /private/var/folders/tm/5dps4bkx489b0qrcxckh0gq40000gn/T/pip-install-_jc8w8x_/pycairo_d49284ba574c41e5a568c56c994a2f90
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-cpython-39
  creating build/lib.macosx-10.9-x86_64-cpython-39/cairo
  copying cairo/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/cairo
  copying cairo/__init__.pyi -> build/lib.macosx-10.9-x86_64-cpython-39/cairo
  copying cairo/py.typed -> build/lib.macosx-10.9-x86_64-cpython-39/cairo
  running build_ext
  'pkg-config' not found.
  Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
Successfully built dictdiffer NeuroM pyemf3
Failed to build pycairo
ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly
```
Note that `/.../` in the above paths is simply my editing out my local path.

brew indicates I have `cairo 1.16.0_5`, which seems like it should work?

**Comment by ZeitgeberH** [comment]
Sorry i don't have Mac OS dev env now. 
I think this is  OS dependent issue for `pycairo`. They suggest install both `cairo` and `pkg-config` for Mac here (https://pycairo.readthedocs.io/en/latest/getting_started.html) 
`brew install cairo pkg-config`
If that doesn't work, can you try installing `pycairo` from conda? https://anaconda.org/conda-forge/pycairo

**Comment by marcel-goldschen-ohm** [comment]
`brew install cairo pkg-config` allowed `pip install patchview` to proceed without errors. Yay! However, running `patchview` now fails with the error:
```
Traceback (most recent call last):
  File "/Users/.../opt/miniconda3/envs/patchview/bin/patchview", line 5, in <module>
    from patchview import pvGUI
  File "/Users/.../opt/miniconda3/envs/patchview/lib/python3.8/site-packages/patchview/__init__.py", line 1, in <module>
    from . import patchview
  File "/Users/.../opt/miniconda3/envs/patchview/lib/python3.8/site-packages/patchview/patchview.py", line 17, in <module>
    from patchview.HekaIO.HekaHelpers import HekaBundleInfo
  File "/Users/.../opt/miniconda3/envs/patchview/lib/python3.8/site-packages/patchview/HekaIO/HekaHelpers.py", line 20, in <module>
    class HekaBundleInfo(object):
  File "/Users/.../opt/miniconda3/envs/patchview/lib/python3.8/site-packages/patchview/HekaIO/HekaHelpers.py", line 166, in HekaBundleInfo
    def getTraceRecordingMode(self, idx:list[int, int, int, int]):
TypeError: 'type' object is not subscriptable
```

**Comment by marcel-goldschen-ohm** [comment]
Ok, so type hinting error was fixed by upgrading to python 3.10. Also, my apologies as I now see that some of these suggestions are in the latest docs. I found patchview via another site (I don't recall which one, might have been neural data without borders), which linked me to what are clearly stale instructions (python 3.8, etc.). My bad. Unfortunately, after upgrading to python 3.10 and following the latest docs, I still get the following error when attempting to run `patchview`:
```
Traceback (most recent call last):
  File "/Users/.../opt/miniconda3/envs/patchview/bin/patchview", line 5, in <module>
    from patchview import pvGUI
  File "/Users/.../opt/miniconda3/envs/patchview/lib/python3.10/site-packages/patchview/__init__.py", line 1, in <module>
    from . import patchview
  File "/Users/.../opt/miniconda3/envs/patchview/lib/python3.10/site-packages/patchview/patchview.py", line 74, in <module>
    matplotlib.use("QtCairo") ## for svg export
  File "/Users/.../opt/miniconda3/envs/patchview/lib/python3.10/site-packages/matplotlib/__init__.py", line 1237, in use
    plt.switch_backend(name)
  File "/Users/.../opt/miniconda3/envs/patchview/lib/python3.10/site-packages/matplotlib/pyplot.py", line 279, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'QtCairo' which requires the 'qt' interactive framework, as 'macosx' is currently running
```
The same error persists after running `pip uninstall pyqt5 pyqt5-qt5 pyqtwebengine-qt5 pyqt5-sip` and `pip install pyqt5 pyqtwebengine pyqt5-sip` as suggested in the docs.

**Comment by ZeitgeberH** [comment]
Thanks very much for your interests. 
I have not worked on the PyPI package for a while and just updated the documentation this morning after fixed the errors. So the apology is mine :)
Yes, In for Python 3.8,  I can reproduce this error, but with Python 3.10 it is fine.

The 'QtCairo' error seems has something to do with Matplotlib's backend. Could you try if matplotlib works in your env?

**Comment by ZeitgeberH** [comment]
From the error message, one suggestion would be to change the line 74 in `patchview.py` 
from 
`matplotlib.use("QtCairo") ## for svg export`
to
`matplotlib.use("macosx")`
As `macosx` is your default backend. 

Then recompile from source.

**Comment by marcel-goldschen-ohm** [comment]
`matplotlib.use("macosx")` worked! Thanks. The GUI now loads. I'll have to play around with it now ;)

Cheers!
