### ISSUE TITLE
Connectivity analysis unavailable

### ISSUE THREAD

**Issue by LouisonPineau** [ZeitgeberH/patchview#19]
Hello,

I started using Patchview 0.3.0 (stand along app) to analyse data from tests experiments on a new multipatch setup. I was able to analyse the firing pattern of the recorded cells but I wasn't able to perform connectivity analysis. It seems I can load the files but the list of sweeps doesn't appear in the connection tab. The connectivity option also doesn't appear when I right-click on the serie I want to analyse. I haven't tried to use the source code for now so I don't know if my problem is specific to the stand-along app. I tried running the program on 2 different computers (Windows 11 and 10) but the same problem appears on both.

Thanks in advance for your help.

Best regards,
Louison Pineau

**Comment by ZeitgeberH** [comment]
Hi Louison,
Thanks for reaching out.
My guess is that the name for your connectivity protocol is not among the default names for connectivity protocols (_'STI', 'Sti', 'Cc', 'cc'_). You could add the protocol name for your experiment in the [configuration file](https://github.com/ZeitgeberH/patchview/blob/790543176008668b68f3ac0d09a079972a4b6fda/patchview/Data/patchview.yaml#L10). This [documentation page](https://patchview.readthedocs.io/en/latest/installation.html#configuration) describes how to find the configuration file dependent on your OS. After that, restart Patchview to see if sweeps show up. 
Feel free to share a representative sample of your data to me if that doesn't solve the problem. 
Best,
Z

**Comment by LouisonPineau** [comment]
Thank you for your answer, I modified the .yaml files (there were two, one in the extracted patchview directory and the other one in the C:\Users\...\AppData\Local\Patchview\Patchview folder. I added the name of my protocols and restarted the program but the problem remains. I attached an example of a recording I did. It contains some basic protocols (depolarising steps for firing pattern and another one where I patched two cells simultaneously to test connectivity). I also noticed that I have a problem with the voltage scale, it looks like its mutiplied by 2 but I don't really know where it's coming from.

Best,
Louison

[Username_2024-07-23_001.zip](https://github.com/user-attachments/files/16372373/Username_2024-07-23_001.zip)

**Comment by ZeitgeberH** [comment]
Louison, 
Sorry I wasn't clear about the name last time. The name of protocols are the "Label" that you created in the recording software.  This is shown in Patchview when you loaded the data in single file mode (double clicking the file).  From you data, the firing pattern is labeled as "CCsteps", connectivity is labeled as "CCstep_pair". Please add these two to the config file, in Firing Pattern and Connection respectively. 
![Screenshot 2024-07-25 192540](https://github.com/user-attachments/assets/d64a81b0-715d-4b45-abb6-32529eacd683)

For connectivity analysis, we usually record a separate file for each connectivity test; then put all those files in a folder. Then using the [batching loading](https://patchview.readthedocs.io/en/latest/tutorials.html) method to load them.  If you put your file in a folder, then right clicking the folder, you will get a dialog window to choose; just click OK, then the contents will be loaded in the right panel (Make sure you add the correct label to the connectivity list as mentioned above). From there, you can click any of those to load it to the right panel to view it.  I do noticed the connectivity analysis on the data lead to errors and need find time to debug it. 

![Screenshot 2024-07-25 194016](https://github.com/user-attachments/assets/d3491064-ccce-44fd-bf8a-d9cb115b77a4)

Could you elaborate on the voltage scale issue? Is it in all recordings.

**Comment by LouisonPineau** [comment]
Hi,

Thanks a lot for your help ! I already added the labels as you suggested in the configuration files (that's what I meant by adding the "name of my protocols", sorry I wasn't super clear).

![image](https://github.com/user-attachments/assets/24370cfd-c600-4b82-b046-285a91776c55)
![image](https://github.com/user-attachments/assets/7363d20b-8380-47cb-9b29-6be405fa040d)

I will record the firing and connectivity parts of the recordings in seperate files for my next experiment and see if this helps (I'll let you know of course). Concerning the voltage scale issue, it's on all my recordings. When I recorded the cells, they had a Vm around -60 mV. When I open the files in Patchview, the baseline is around -100 -120 mV so around twice what I had in Patchmaster. I'm inclined to think that this might come from my Patchmaster config or my amplifier, I will investigate this also.

**Comment by ZeitgeberH** [comment]
I see. It is strange that the baseline is ~ -60 mV for trace 2, but ~ -120 mV in trace 1 which is the stimulation channel.
Also, there is significant drift of baseline across sweeps in the firing pattern data. 


![Screenshot 2024-07-26 070803](https://github.com/user-attachments/assets/628fc983-3b03-4cec-a22f-40ab2571d27f)


The connectivity analysis will need to know which channel (among all traces simultaneously recorded) is the one that receives injected current.  If there is only two channels, maybe it is not necessary to have a separate file for each recording, assuming the first channel is always the one gets injected current.

**Comment by LouisonPineau** [comment]
So, I recorded some other cells last Friday (the files are attached). The first file (name ending with _004) contains the firing protocol. This time the baselines are correct and the analysis detects all the APs. The second file contains the connectivity protocol, you'll see that in each serie, the first channel has a very hyperpolarised baseline although I did not change the holding current. Fort he connectivity analysis, the program now recognizes the label but when I try to launch the connectivity batch analysis, the program goes to the connection analysis page and nothing happens. Do you think the basleine problem might be responsible for this ?
[Username_2024-07-26_004 and 005.zip](https://github.com/user-attachments/files/16410815/Username_2024-07-26_004.and.005.zip)

**Comment by ZeitgeberH** [comment]
I think baseline for stimulation channel should not matter for the connectivity analysis, although it is strange that it is shown at < -120 mV. The errors (i think) is due to different recording conventions.  I changed some default settings so now it should be able to analyze your data.

![Screenshot 2024-07-29 202634](https://github.com/user-attachments/assets/9449058c-4116-4ae5-93e8-f7f5a2640f2f)

**Comment by LouisonPineau** [comment]
What are the default settings you changed ?

**Comment by ZeitgeberH** [comment]
> What are the default settings you changed ?

Default about the stimulation channel is now set as the first one.

**Comment by ZeitgeberH** [comment]
Try the new release here: https://github.com/ZeitgeberH/patchview/releases/download/v0.3.3/PatchviewV0.3.3.7z
Hope that helps.  One slight comment, for connectivity analysis, we usually use a pulse that is very short ~2ms.

**Comment by LouisonPineau** [comment]
It's working now ! Thank you very much for your help and he advices ! I will modify my protocol to shorten the stimulation.
