### ISSUE TITLE
[JOSS review] Requirement not found when installing with pip on python 3.10.5

### ISSUE THREAD

**Issue by janfreyberg** [ZeitgeberH/patchview#2]
Hi there,

as part of the JOSS review I am going to open issues as I go through the review checklist.

I am using python 3.10.5, and when running `pip install patchview`, I see:

```
ERROR: Could not find a version that satisfies the requirement PySide2==5.15.2 (from patchview) (from versions: 0.0.0a1, 5.11.0, 5.11.1, 5.11.2, 5.12.0, 5.12.1, 5.12.2, 5.12.3, 5.12.4, 5.12.5, 5.12.6, 5.13.0, 5.13.1, 5.13.2, 5.15.2.1)
ERROR: No matching distribution found for PySide2==5.15.2
```

It looks like the dependency version requirements need to be relaxed a bit?

Thanks,
Jan

**Comment by ZeitgeberH** [comment]
Hi Jan,
Thanks very much for reviewing my code. 
I've relaxed the dependency requirement for Pyside2, Pyqt and pyqtgraph etc in the new version.
I tested it for Python 3.8 -3.10. PyPi package is also updated (now 0.2.5). 
Please let me know if that works on your end.
Best,
Ming

**Comment by ZeitgeberH** [comment]
Hi Jan,
Thanks very much for reviewing my code.
I've relaxed the dependency requirement for Pyside2, Pyqt and pyqtgraph etc in the new version.
I tested it for Python 3.8 -3.10. PyPi package is also updated (now 0.2.5).
Please let me know if that works on your end.
Best,
Ming

**Comment by janfreyberg** [comment]
Thanks, this works now :)
