### ISSUE TITLE
[JOSS review] Installation on Linux fails due to `PyOpenGL_accelerate` dependency

### ISSUE THREAD

**Issue by mstimberg** [ZeitgeberH/patchview#3]
Hi there,
second JOSS reviewer here. I ran into a small issue installing the software via `pip install patchview`. The dependecy list refers to `PyOpenGL_accelerate>=3.1.6`, but this version is only installable on Windows (only wheels for Windows here: https://pypi.org/project/PyOpenGL-accelerate/#files). Earlier versions also provided a source package, not sure whether they would have been installable. Either way, `patchview` seems to be working fine without it (as the name suggests, I guess the package is only for optional acceleration). Maybe consider making the dependency optional or add something like `; sys_platform == 'win32'` (see [PEP 508](https://peps.python.org/pep-0508/)).

**Comment by ZeitgeberH** [comment]
Hi Marcel,
Thanks for reviewing my code.
I've added platform dependent flag as you suggested.  Git repo and PyPI package has been updated accordingly.
