### ISSUE TITLE
[Joss Review] Add link to sample data to documentation

### ISSUE THREAD

**Issue by janfreyberg** [ZeitgeberH/patchview#4]
Hi there,

in going through the documentation to test functionality, I was missing a link to sample data. I downloaded sample data from the `tests` directory, but it may be useful to add a link to these sample files in the documentation, ideally with an explanation of what to expect in each file.

Thank you,
Jan

**Comment by ZeitgeberH** [comment]
Hi Jan,
I've enhanced documentation (in [_Get started/Test dataset_](https://patchview.readthedocs.io/en/latest/installation.html#test-dataset) section  ) as you suggested above.  
Thank you!
Zeta
