### ISSUE TITLE
[JOSS review] test_readNwb fails on first run

### ISSUE THREAD

**Issue by mstimberg** [ZeitgeberH/patchview#8]
The test suite checks whether reading the `test.nwb` file works, but this file is created by `test_writeNwb` which does not necessarily run before it (at least on my machine, tests run in alphabetical order). 

openjournals/joss-reviews#4706

**Comment by ZeitgeberH** [comment]
Thanks for the catch. This has been fixed at [c8226f0](https://github.com/ZeitgeberH/patchview/commit/c8226f012f3b1864358138ae424ebb2574923f22)

**Comment by mstimberg** [comment]
Thanks, that fixed the issue for me.
