### ISSUE TITLE
[JOSS review] cannot test connection analysis

### ISSUE THREAD

**Issue by mstimberg** [ZeitgeberH/patchview#9]
As far as I can see, there is no multi-cell test data, so I don't have a way to test the connection analysis part (maybe generate some artificial data?).

openjournals/joss-reviews#4706

**Comment by ZeitgeberH** [comment]
A folder of test files recorded from a multi-patch experiment has been uploaded in[ tests/data/connection_test](https://github.com/ZeitgeberH/patchview/tree/main/tests/data/connection_test).
Documentation of the [analysis](https://patchview.readthedocs.io/en/latest/tutorials.html#monosynaptic-connection-detection) and [data](https://patchview.readthedocs.io/en/latest/installation.html#test-dataset) has been updated accordingly.
Thanks!

**Comment by mstimberg** [comment]
Thanks, I was able to test the functionality with the provided data.
